#!/usr/bin/env bash
# Summary: Explain how the current Ruby version is set
set -e
[ -n "$LTENV_DEBUG" ] && set -x

if [ -n "$LTENV_VERSION" ]; then
  echo "LTENV_VERSION environment variable"
else
  ltenv-version-file
fi
