#!/usr/bin/env bash
# Summary: List hook scripts for a given ltenv command
# Usage: ltenv hooks <command>

set -e
[ -n "$LTENV_DEBUG" ] && set -x

# Provide ltenv completions
if [ "$1" = "--complete" ]; then
  echo exec
  echo rehash
  echo which
  exit
fi

LTENV_COMMAND="$1"
if [ -z "$LTENV_COMMAND" ]; then
  ltenv-help --usage hooks >&2
  exit 1
fi

if ! enable -f "${BASH_SOURCE%/*}"/ltenv-realpath.dylib realpath 2>/dev/null; then
  if [ -n "$LTENV_NATIVE_EXT" ]; then
    echo "ltenv: failed to load \`realpath' builtin" >&2
    exit 1
  fi
READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "ltenv: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

realpath() {
  local cwd="$PWD"
  local path="$1"
  local name

  while [ -n "$path" ]; do
    name="${path##*/}"
    [ "$name" = "$path" ] || cd "${path%/*}"
    path="$(resolve_link "$name" || true)"
  done

  echo "${PWD}/$name"
  cd "$cwd"
}
fi

IFS=: hook_paths=($LTENV_HOOK_PATH)

shopt -s nullglob
for path in "${hook_paths[@]}"; do
  for script in "$path/$LTENV_COMMAND"/*.bash; do
    realpath "$script"
  done
done
shopt -u nullglob
