#!/usr/bin/env bash
# Summary: Configure the shell environment for ltenv
# Usage: eval "$(ltenv init - [--no-rehash] [<shell>])"

set -e
[ -n "$LTENV_DEBUG" ] && set -x

# Provide ltenv completions
if [ "$1" = "--complete" ]; then
  echo -
  echo --no-rehash
  echo bash
  echo fish
  echo ksh
  echo zsh
  exit
fi

print=""
no_rehash=""
for args in "$@"
do
  if [ "$args" = "-" ]; then
    print=1
    shift
  fi

  if [ "$args" = "--no-rehash" ]; then
    no_rehash=1
    shift
  fi
done

shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps c -p "$PPID" -o 'ucomm=' 2>/dev/null || true)"
  shell="${shell##-}"
  shell="${shell%% *}"
  shell="${shell:-$SHELL}"
  shell="${shell##*/}"
fi

root="${0%/*}/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    if [ -f "${HOME}/.bashrc" ] && [ ! -f "${HOME}/.bash_profile" ]; then
      profile='~/.bashrc'
    else
      profile='~/.bash_profile'
    fi
    ;;
  zsh )
    profile='~/.zshrc'
    ;;
  ksh )
    profile='~/.profile'
    ;;
  fish )
    profile='~/.config/fish/config.fish'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load ltenv automatically by appending"
    echo "# the following to ${profile}:"
    echo
    case "$shell" in
    fish )
      echo 'status --is-interactive; and . (ltenv init -|psub)'
      ;;
    * )
      echo 'eval "$(ltenv init -)"'
      ;;
    esac
    echo
  } >&2

  exit 1
fi

mkdir -p "${LTENV_ROOT}/"shims

case "$shell" in
fish )
  echo "setenv PATH '${LTENV_ROOT}/shims' \$PATH"
  echo "setenv LTENV_SHELL $shell"
;;
* )
  echo 'export PATH="'${LTENV_ROOT}'/shims:${PATH}"'
  echo "export LTENV_SHELL=$shell"
;;
esac

completion="${root}/completions/ltenv.${shell}"
if [ -r "$completion" ]; then
  case "$shell" in
  fish ) echo ". '$completion'" ;;
  *    ) echo "source '$completion'" ;;
  esac
fi

if [ -z "$no_rehash" ]; then
  echo 'command ltenv rehash 2>/dev/null'
fi

commands=(`ltenv-commands --sh`)
case "$shell" in
fish )
  cat <<EOS
function ltenv
  set command \$argv[1]
  set -e argv[1]

  switch "\$command"
  case ${commands[*]}
    . (ltenv "sh-\$command" \$argv|psub)
  case '*'
    command ltenv "\$command" \$argv
  end
end
EOS
  ;;
ksh )
  cat <<EOS
function ltenv {
  typeset command
EOS
  ;;
* )
  cat <<EOS
ltenv() {
  local command
EOS
  ;;
esac

if [ "$shell" != "fish" ]; then
IFS="|"
cat <<EOS
  command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval "\$(ltenv "sh-\$command" "\$@")";;
  *)
    command ltenv "\$command" "\$@";;
  esac
}
EOS
fi
