#!/usr/bin/env bash
# Usage: ltenv completions <command> [arg1 arg2...]

set -e
[ -n "$LTENV_DEBUG" ] && set -x

COMMAND="$1"
if [ -z "$COMMAND" ]; then
  ltenv-help --usage completions >&2
  exit 1
fi

# Provide ltenv completions
if [ "$COMMAND" = "--complete" ]; then
  exec ltenv-commands
fi

COMMAND_PATH="$(command -v "ltenv-$COMMAND" || command -v "ltenv-sh-$COMMAND")"

# --help is provided automatically
echo --help

if grep -iE "^([#%]|--|//) provide ltenv completions" "$COMMAND_PATH" >/dev/null; then
  shift
  exec "$COMMAND_PATH" --complete "$@"
fi
