#!/usr/bin/env bash
set -e
[ -n "$LTENV_DEBUG" ] && set -x

# Provide ltenv completions
if [ "$1" = "--complete" ]; then
  exec ltenv-rehash --complete
fi

shell="$(basename "${LTENV_SHELL:-$SHELL}")"

# When ltenv shell integration is enabled, delegate to ltenv-rehash,
# then tell the shell to empty its command lookup cache.
ltenv-rehash

case "$shell" in
fish )
  # no rehash support
  ;;
* )
  echo "hash -r 2>/dev/null || true"
  ;;
esac
