#!/usr/bin/env bash
# Summary: Show the current Ruby version
set -e
[ -n "$LTENV_DEBUG" ] && set -x

if [ -z "$LTENV_VERSION" ]; then
  LTENV_VERSION_FILE="$(ltenv-version-file)"
  LTENV_VERSION="$(ltenv-version-file-read "$LTENV_VERSION_FILE" || true)"
fi

if [ -z "$LTENV_VERSION" ] || [ "$LTENV_VERSION" = "system" ]; then
  echo "system"
  exit
fi

## DG ##
##LTENV_COMMAND_PATH=`grep "^$LTENV_VERSION " $LTENV_VERSIONS_FILE | awk '{ print $2 }'`
##LTENV_COMMAND_TEXMFCNF=`grep "^$LTENV_VERSION " $LTENV_VERSIONS_FILE | awk '{ print $3 }'`

##export LTENV_COMMAND_PATH
##export LTENV_COMMAND_TEXMFCNF

echo $LTENV_VERSION

#version_exists() {
#  local version="$1"
#  [ -d "${LTENV_ROOT}/versions/${version}" ]
#}
#
##if version_exists "$LTENV_VERSION"; then
##  echo "$LTENV_VERSION"
##elif version_exists "${LTENV_VERSION#ruby-}"; then
##  echo "${LTENV_VERSION#ruby-}"
##else
##  echo "ltenv: version \`$LTENV_VERSION' is not installed (set by $(ltenv-version-origin))" >&2
##  exit 1
##fi
