#!/usr/bin/env bash
# Summary: Detect the file that sets the current ltenv version
set -e
[ -n "$LTENV_DEBUG" ] && set -x

find_local_version_file() {
  local root="$1"
  while true; do
    [[ "$root" =~ ^//[^/]*$ ]] && break
    if [ -e "${root}/.latex-version" ]; then
      echo "${root}/.latex-version"
      exit
    elif [ -e "${root}/.ltenv-version" ]; then
      echo "${root}/.ltenv-version"
      exit
    fi
    [ -n "$root" ] || break
    root="${root%/*}"
  done
}

find_local_version_file "$LTENV_DIR"
[ "$LTENV_DIR" = "$PWD" ] || find_local_version_file "$PWD"

global_version_file="${LTENV_ROOT}/version"

if [ -e "$global_version_file" ]; then
  echo "$global_version_file"
elif [ -e "${LTENV_ROOT}/global" ]; then
  echo "${LTENV_ROOT}/global"
elif [ -e "${LTENV_ROOT}/default" ]; then
  echo "${LTENV_ROOT}/default"
else
  echo "$global_version_file"
fi
