#!/usr/bin/env bash
# Summary: List existing ltenv shims
# Usage: ltenv shims [--short]

set -e
[ -n "$LTENV_DEBUG" ] && set -x

# Provide ltenv completions
if [ "$1" = "--complete" ]; then
  echo --short
  exit
fi

shopt -s nullglob

for command in "${LTENV_ROOT}/shims/"*; do
  if [ "$1" = "--short" ]; then
    echo "${command##*/}"
  else
    echo "$command"
  fi
done | sort
